name: Ravenair slot scan

on:
  schedule:
    - cron: '*/15 * * * *'           # every 15 minutes, UTC
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest          # still 24.04 but ok

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          pip install playwright==1.37 python-dotenv beautifulsoup4 lxml
          # only the browsers, no system deps
          playwright install chromium

      - name: Run the slot scanner
        run: python mainV2.py
        env:
          LOGIN_EMAIL:     ${{ secrets.LOGIN_EMAIL }}
          LOGIN_PASSWORD:  ${{ secrets.LOGIN_PASSWORD }}
          SMTP_HOST:       ${{ secrets.SMTP_HOST }}
          SMTP_PORT:       ${{ secrets.SMTP_PORT }}
          SMTP_USER:       ${{ secrets.SMTP_USER }}
          SMTP_PASS:       ${{ secrets.SMTP_PASS }}
          SMTP_TO:         ${{ secrets.SMTP_TO }}
          DATE_WINDOW_DAYS: ${{ secrets.DATE_WINDOW_DAYS }}   # optional

      # optional snapshot commit
      - name: Commit updated snapshot
        if: success()
        run: |
          git config user.name  "slot-bot"
          git config user.email "slot-bot@users.noreply.github.com"
          git add slots_latest.txt
          git commit -m "snapshot $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || exit 0
          git push
